education:
  - degree: Bachelor of Science in Computer Science
    institution: University of Rochester
    year: "September 2003 – May 2007"
  - degree: Bachelor of Arts in Linguistics
    institution: University of Rochester
    year: "September 2003 – May 2007"
