education:
  - degree: LLM in United States Law (International Law and Human Rights)
    institution: Santa Clara University School of Law
    year: "2015 – 2016"
  - degree: Abogada (LLB equivalent), orientation in Public International Law and Business Law
    institution: Facultad de Derecho, Universidad de Buenos Aires
    year: "2007 – 2012"
  - degree: Diplomatura en Derecho Ambiental
    institution: Universidad de Buenos Aires
    year: "2021"
  - degree: Diplomatura en Igualdad y no Discriminación
    institution: Universidad de Buenos Aires
    year: "2019"
  - degree: Programa de Actualización en Derecho Informático
    institution: Universidad de Buenos Aires
    year: "2014 – 2015"
  - degree: Coursework
    institution: Foothill College
    year: "2004 – 2005"
  - degree: Perito Mercantil (Contabilidad y Gestión Empresarial)
    institution: Instituto San José D-46
    year: "1999 – 2003"

