filters:
  - name: health_movati
    match:
      query: "from:(movati) OR from:(movati.com)"
    action:
      add: ["Health/Movati", "Health"]
  - name: health_jane
    match:
      query: "from:(janeapp) OR from:(janeapp.com)"
    action:
      add: ["Health/Jane", "Health"]
  - name: personal_alumni
    match:
      query: "from:(alumni) OR subject:(alumni)"
    action:
      add: ["Personal/Alumni", "Personal"]
