filters:
- name: suggest:e.fossil.com
  match:
    query: from:(e.fossil.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:linkedin.com
  match:
    query: from:(linkedin.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:email.jcpenney.com
  match:
    query: from:(email.jcpenney.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:rom.on.ca
  match:
    query: from:(rom.on.ca)
  action:
    add:
    - Lists/Newsletters
- name: suggest:movies.fandango.com
  match:
    query: from:(movies.fandango.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:news.supermercadosdia.com.ar
  match:
    query: from:(news.supermercadosdia.com.ar)
  action:
    add:
    - Lists/Commercial
- name: suggest:email.stackcommerce.com
  match:
    query: from:(email.stackcommerce.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:baggu.com
  match:
    query: from:(baggu.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:rewardingyouropinions.ca
  match:
    query: from:(rewardingyouropinions.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:ccsyr.org
  match:
    query: from:(ccsyr.org)
  action:
    add:
    - Lists/Newsletters
- name: suggest:email.bose.com
  match:
    query: from:(email.bose.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:mail.futureparty.com
  match:
    query: from:(mail.futureparty.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:drsquatch.com
  match:
    query: from:(drsquatch.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:mail.aircanada.com
  match:
    query: from:(mail.aircanada.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:thedailybeast.com
  match:
    query: from:(thedailybeast.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:email.thestar.com
  match:
    query: from:(email.thestar.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:interactive.wsj.com
  match:
    query: from:(interactive.wsj.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:washingtonpost.com
  match:
    query: from:(washingtonpost.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:amazon.ca
  match:
    query: from:(amazon.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:partnernews.airmiles.ca
  match:
    query: from:(partnernews.airmiles.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:tilley.com
  match:
    query: from:(tilley.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.shopcuup.com
  match:
    query: from:(e.shopcuup.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:emails.hertz.com
  match:
    query: from:(emails.hertz.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:ocasiocortez.com
  match:
    query: from:(ocasiocortez.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:programnews.airmiles.ca
  match:
    query: from:(programnews.airmiles.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:email.paramountplus.com
  match:
    query: from:(email.paramountplus.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.newyorktimes.com
  match:
    query: from:(e.newyorktimes.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:duolingo.com
  match:
    query: from:(duolingo.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:emails.better.com
  match:
    query: from:(emails.better.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:email.livenation.com
  match:
    query: from:(email.livenation.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.daveandbusters.com
  match:
    query: from:(e.daveandbusters.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:facebookmail.com
  match:
    query: from:(facebookmail.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:email.etsy.com
  match:
    query: from:(email.etsy.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:reply.royalcaribbeanmarketing.com
  match:
    query: from:(reply.royalcaribbeanmarketing.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:email.gotransit.com
  match:
    query: from:(email.gotransit.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:swissmedical.com.ar
  match:
    query: from:(swissmedical.com.ar)
  action:
    add:
    - Lists/Commercial
- name: suggest:offers.eddiebauer.com
  match:
    query: from:(offers.eddiebauer.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:stockstory.org
  match:
    query: from:(stockstory.org)
  action:
    add:
    - Lists/Newsletters
- name: suggest:canadaluggagedepot.ca
  match:
    query: from:(canadaluggagedepot.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:ridgewallet.ca
  match:
    query: from:(ridgewallet.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:marketing.mlbemail.com
  match:
    query: from:(marketing.mlbemail.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:message.bloomberg.com
  match:
    query: from:(message.bloomberg.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:e.email-td.com
  match:
    query: from:(e.email-td.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:flareaudio.com
  match:
    query: from:(flareaudio.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:email.americanexpress.com
  match:
    query: from:(email.americanexpress.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:gunnar.com
  match:
    query: from:(gunnar.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:email.pcoptimum.ca
  match:
    query: from:(email.pcoptimum.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.cherokee.org
  match:
    query: from:(e.cherokee.org)
  action:
    add:
    - Lists/Commercial
- name: suggest:ekster.com
  match:
    query: from:(ekster.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:email.amctheatres.com
  match:
    query: from:(email.amctheatres.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:atlasobscura.com
  match:
    query: from:(atlasobscura.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.pcfinancial.ca
  match:
    query: from:(e.pcfinancial.ca)
  action:
    add:
    - Lists/Newsletters
- name: suggest:marketing.basspro.com
  match:
    query: from:(marketing.basspro.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:mail.allbirds.com
  match:
    query: from:(mail.allbirds.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:westcoastkids.ca
  match:
    query: from:(westcoastkids.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:emails.underarmour.com
  match:
    query: from:(emails.underarmour.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:celpip.ca
  match:
    query: from:(celpip.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:info15.citi.com
  match:
    query: from:(info15.citi.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:email.legoland.com
  match:
    query: from:(email.legoland.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:mp1.tripadvisor.com
  match:
    query: from:(mp1.tripadvisor.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:cmail.bark.com
  match:
    query: from:(cmail.bark.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:aadvantageeshopping.com
  match:
    query: from:(aadvantageeshopping.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:emails.ca.skechers.com
  match:
    query: from:(emails.ca.skechers.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:calpaktravel.com
  match:
    query: from:(calpaktravel.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.economist.com
  match:
    query: from:(e.economist.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.emirates.email
  match:
    query: from:(e.emirates.email)
  action:
    add:
    - Lists/Commercial
- name: suggest:promo.thestar.com
  match:
    query: from:(promo.thestar.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:o.delta.com
  match:
    query: from:(o.delta.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.xbox.com
  match:
    query: from:(e.xbox.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:bogsfootwear.ca
  match:
    query: from:(bogsfootwear.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:google.com
  match:
    query: from:(google.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:urbanarmorgear.com
  match:
    query: from:(urbanarmorgear.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:nintendo.net
  match:
    query: from:(nintendo.net)
  action:
    add:
    - Lists/Commercial
- name: suggest:news.email.ikea.ca
  match:
    query: from:(news.email.ikea.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:harderforcongress.com
  match:
    query: from:(harderforcongress.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.lululemon.com
  match:
    query: from:(e.lululemon.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:hmbartglass.com
  match:
    query: from:(hmbartglass.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:news.arcteryx.com
  match:
    query: from:(news.arcteryx.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:bellroy.com
  match:
    query: from:(bellroy.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:museumofplay.org
  match:
    query: from:(museumofplay.org)
  action:
    add:
    - Lists/Commercial
- name: suggest:cscrewards.coldstonecreamery.com
  match:
    query: from:(cscrewards.coldstonecreamery.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:primevideo.com
  match:
    query: from:(primevideo.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:aclu.org
  match:
    query: from:(aclu.org)
  action:
    add:
    - Lists/Commercial
- name: suggest:mail.dazn.com
  match:
    query: from:(mail.dazn.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:send.topodesigns.ca
  match:
    query: from:(send.topodesigns.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.gear.blizzard.com
  match:
    query: from:(e.gear.blizzard.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:mail.zillow.com
  match:
    query: from:(mail.zillow.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:e.malwarebytes.com
  match:
    query: from:(e.malwarebytes.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:attn.us.lg.com
  match:
    query: from:(attn.us.lg.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:email-caasco.com
  match:
    query: from:(email-caasco.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:occu.org
  match:
    query: from:(occu.org)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.giffords.org
  match:
    query: from:(e.giffords.org)
  action:
    add:
    - Lists/Commercial
- name: suggest:rickshawbags.com
  match:
    query: from:(rickshawbags.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:emails.ugg.com
  match:
    query: from:(emails.ugg.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:americas.comm.dell.com
  match:
    query: from:(americas.comm.dell.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:substack.com
  match:
    query: from:(substack.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:support.heifer.org
  match:
    query: from:(support.heifer.org)
  action:
    add:
    - Lists/Commercial
- name: suggest:photobucket.com
  match:
    query: from:(photobucket.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.votevets.org
  match:
    query: from:(e.votevets.org)
  action:
    add:
    - Lists/Commercial
- name: suggest:ihotoffers.com
  match:
    query: from:(ihotoffers.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:mcmap.chase.com
  match:
    query: from:(mcmap.chase.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:soslprospect.salliemae.com
  match:
    query: from:(soslprospect.salliemae.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.mail.washingtonpost.com
  match:
    query: from:(e.mail.washingtonpost.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:recycledfirefighter.com
  match:
    query: from:(recycledfirefighter.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:email.rocketlawyer.com
  match:
    query: from:(email.rocketlawyer.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:eb.notices.rochester.edu
  match:
    query: from:(eb.notices.rochester.edu)
  action:
    add:
    - Lists/Newsletters
- name: suggest:em.peoplesjewellers.com
  match:
    query: from:(em.peoplesjewellers.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:audible.com
  match:
    query: from:(audible.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:email.aadvantagecruises.com
  match:
    query: from:(email.aadvantagecruises.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:ourrevolution.com
  match:
    query: from:(ourrevolution.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:woolly.clothing
  match:
    query: from:(woolly.clothing)
  action:
    add:
    - Lists/Commercial
- name: suggest:hankypanky.com
  match:
    query: from:(hankypanky.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:info6.citi.com
  match:
    query: from:(info6.citi.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:emails.rakuten.ca
  match:
    query: from:(emails.rakuten.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:mail.marvel.com
  match:
    query: from:(mail.marvel.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:glassdoor.com
  match:
    query: from:(glassdoor.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:m.learn.coursera.org
  match:
    query: from:(m.learn.coursera.org)
  action:
    add:
    - Lists/Commercial
- name: suggest:plans.eventbrite.com
  match:
    query: from:(plans.eventbrite.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:jungleoutlet.com
  match:
    query: from:(jungleoutlet.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:email.adobe.com
  match:
    query: from:(email.adobe.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:m.starbucks.com
  match:
    query: from:(m.starbucks.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:m.massageaddict.ca
  match:
    query: from:(m.massageaddict.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:ridge.com
  match:
    query: from:(ridge.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:emails.goaaa.com
  match:
    query: from:(emails.goaaa.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:offers.bayareanewsgroup.com
  match:
    query: from:(offers.bayareanewsgroup.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:saxxunderwear.ca
  match:
    query: from:(saxxunderwear.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:saxxunderwear.com
  match:
    query: from:(saxxunderwear.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.shoppersdrugmart.ca
  match:
    query: from:(e.shoppersdrugmart.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.walmart.ca
  match:
    query: from:(e.walmart.ca)
  action:
    add:
    - Lists/Newsletters
- name: suggest:email.meta.com
  match:
    query: from:(email.meta.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:news.anker.com
  match:
    query: from:(news.anker.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:email.mint.ca
  match:
    query: from:(email.mint.ca)
  action:
    add:
    - Lists/Newsletters
- name: suggest:nplon.patronpoint-mail.com
  match:
    query: from:(nplon.patronpoint-mail.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:e.journie.ca
  match:
    query: from:(e.journie.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.dji.com
  match:
    query: from:(e.dji.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:subs.subway.com
  match:
    query: from:(subs.subway.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:loyalty.ms.aa.com
  match:
    query: from:(loyalty.ms.aa.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:30orless.com
  match:
    query: from:(30orless.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:e.314actionfund.org
  match:
    query: from:(e.314actionfund.org)
  action:
    add:
    - Lists/Commercial
- name: suggest:digital.costco.com
  match:
    query: from:(digital.costco.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:clarks.com
  match:
    query: from:(clarks.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:active.com
  match:
    query: from:(active.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:contact.loccitane.com
  match:
    query: from:(contact.loccitane.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:stanley1913.com
  match:
    query: from:(stanley1913.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:timbuk2.com
  match:
    query: from:(timbuk2.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:westernrise.com
  match:
    query: from:(westernrise.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:trueclassictees.com
  match:
    query: from:(trueclassictees.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:us.e.sharkninja.com
  match:
    query: from:(us.e.sharkninja.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:info.cibc.com
  match:
    query: from:(info.cibc.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:e.dsw.ca
  match:
    query: from:(e.dsw.ca)
  action:
    add:
    - Lists/Commercial
- name: suggest:nytimes.com
  match:
    query: from:(nytimes.com)
  action:
    add:
    - Lists/Newsletters
- name: suggest:ca.e.sharkninja.com
  match:
    query: from:(ca.e.sharkninja.com)
  action:
    add:
    - Lists/Commercial
- name: suggest:novedades.santander.com.ar
  match:
    query: from:(novedades.santander.com.ar)
  action:
    add:
    - Lists/Commercial
- name: suggest:emails.reebok.com
  match:
    query: from:(emails.reebok.com)
  action:
    add:
    - Lists/Commercial
