filters:
  - name: kids_yrdsb_forward
    match:
      from: "yrdsb.ca"
    action:
      add: ["Kids-School"]
      forward: "vanesaecheveste@hotmail.com"
  - name: kids_ycdsb_forward
    match:
      from: "ycdsb.ca"
    action:
      add: ["Kids-School"]
      forward: "vanesaecheveste@hotmail.com"
