filters:
  - name: "Parent Label: Kids from Kids/Activities"
    match:
      query: 'label:"Kids/Activities"'
    action:
      add: ['Kids']

  - name: "Parent Label: Lists from Commercial/Newsletters"
    match:
      query: 'label:"Lists/Commercial" OR label:"Lists/Newsletters"'
    action:
      add: ['Lists']

  - name: "Parent Label: Kids from Kids/Scouts"
    match:
      query: 'label:"Kids/Scouts"'
    action:
      add: ['Kids']

  - name: "Parent Label: Finance from Finance subs"
    match:
      query: 'label:"Finance/Receipts" OR label:"Finance/Orders" OR label:"Finance/Merchants" OR label:"Finance/Bills" OR label:"Finance/Chase"'
    action:
      add: ['Finance']

  - name: "Parent Label: Alumni from Alumni subs"
    match:
      query: 'label:"Alumni/*"'
    action:
      add: ['Alumni']
