filters:
  - name: Map Activities (Active/RH) to Kids
    match:
      query: 'from:(richmondhill@active.com OR active.com OR richmondhillsoccer.com OR ontariosoccer)'
    action:
      add: ['Kids/Activities']

  - name: Map Therapy/School Resources to Kids
    match:
      query: 'from:(speechaim.com OR psy-ed.com OR 1to1rehab.ca OR rhpl.ca OR moonpreneur.com)'
    action:
      add: ['Kids/Activities']
