labels:
- name: Lists/Commercial
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Lists/Political
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Finance
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Finance/Chase
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Lists/News
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Finance/Bills
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Security/Verification Codes
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids/Scouts
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids/Activities
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Lists/Updates
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids/School
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Lists
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Finance/Citi
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Finance/TD
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Personal
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Personal/VIP/Family
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Personal/Jane
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Personal/Movati
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Personal/UnivOfRochester
  labelListVisibility: labelShow
  messageListVisibility: show
redirects: []
