labels:
- name: Finance/Receipts
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Finance/Orders
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Finance/Merchants
  labelListVisibility: labelShow
  messageListVisibility: show
- name: VIP/Family
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids/School
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Lists/Newsletters
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Lists/Commercial
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Lists/Political
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Finance
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Finance/Chase
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Finance/Metals
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Notes
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Lists/News
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Finance/Bills
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Alumni/UnivOfRochester
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Security/Verification Codes
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids/Scouts
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids/Activities
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids/BrightChamps
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids/RHPL
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids/ActiveRichmondHill
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids/Moonpreneur
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Lists/Updates
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Kids
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Scouts
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Work/HR
  labelListVisibility: labelShow
  messageListVisibility: show
- name: Sent Messages
  labelListVisibility: labelShow
  messageListVisibility: show
- name: SFIF
  labelListVisibility: labelShow
  messageListVisibility: show
- name: '[Gmail]/Sent Mail'
- name: Action/Read Later
  labelListVisibility: labelShow
  messageListVisibility: show
redirects: []
