certifications:
  - name: OCI Architect Associate
    year: "2024"
  - name: Neo4J
    year: "2010"
  - name: Puppet
    year: "2011"
  - name: Java
    year: "2008"
  - name: Advanced Cisco
    year: "2005"
  - name: Franklin Covey
    year: "1996"
  - name: Javascript
    year: "1995"

