education:
  - degree: Bachelor of Science (BS), Computer Science (Incomplete)
    institution: California State Polytechnic University, Pomona
    year: "1988 – 1993"
  - degree: Cognitive Psychology (various classes)
    institution: University of Arkansas
    year: "1999 – 2000"
